#!/usr/bin/env node

/**
 * CSS Builder - Combines separated CSS selector files
 * Concatenates all CSS from content/selectors/ into content/detube.css
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const selectorsDir = path.join(__dirname, '../src/content/css/selectors')
const outputFile = path.join(__dirname, '../src/content/css/detube.css')

// CSS files in order
const cssFiles = [
  'header.css',
  'sidebar.css',
  'homepage.css',
  'video-page.css',
  'channel.css',
  'shorts.css',
  'filters.css'
]

try {
  console.log('🔨 Building combined CSS...')
  
  const cssContent = cssFiles
    .map(file => {
      const filePath = path.join(selectorsDir, file)
      if (!fs.existsSync(filePath)) {
        console.warn(`⚠️  Warning: ${file} not found`)
        return ''
      }
      const content = fs.readFileSync(filePath, 'utf-8')
      return `/* ============== ${file.toUpperCase()} ============== */\n\n${content}\n\n`
    })
    .join('')

  const header = `/* DeTube - Combined CSS Selectors */
/* Generated by build script - DO NOT EDIT MANUALLY */
/* Edit individual files in content/selectors/ instead */
/* Last generated: ${new Date().toISOString()} */

`

  const fullContent = header + cssContent

  fs.writeFileSync(outputFile, fullContent, 'utf-8')
  
  console.log(`✅ CSS build complete: ${outputFile}`)
  console.log(`   Combined ${cssFiles.length} CSS files`)
  console.log(`   File size: ${(fullContent.length / 1024).toFixed(2)} KB`)
  
} catch (error) {
  console.error('❌ CSS build failed:', error.message)
  process.exit(1)
}
